package com.bwie.weidushopping.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bwie.weidushopping.homepage.fragmentwode.allsubclasses.btnwodedizhi.bean.NewsAddress;

import com.bwie.weidushopping.db.NewsAddressDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig newsAddressDaoConfig;

    private final NewsAddressDao newsAddressDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        newsAddressDaoConfig = daoConfigMap.get(NewsAddressDao.class).clone();
        newsAddressDaoConfig.initIdentityScope(type);

        newsAddressDao = new NewsAddressDao(newsAddressDaoConfig, this);

        registerDao(NewsAddress.class, newsAddressDao);
    }
    
    public void clear() {
        newsAddressDaoConfig.clearIdentityScope();
    }

    public NewsAddressDao getNewsAddressDao() {
        return newsAddressDao;
    }

}
